[workspace]
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
name = "pytorch"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[system-requirements]
cuda = "13.0"

[dependencies]
python = ">=3.14.4,<3.15"
torchvision = ">=0.26.0,<0.27"
numpy = ">=2.4.3,<3"
scipy = ">=1.17.1,<2"
pandas = ">=3.0.2,<4"
matplotlib = ">=3.10.9,<4"
pillow = ">=12.2.0,<13"
tqdm = ">=4.67.3,<5"
jupyterlab = ">=4.5.7,<5"
marimo = ">=0.23.5,<0.24"
scikit-learn = ">=1.8.0,<2"
graphviz = ">=14.1.2,<15"
seaborn = ">=0.13.2,<0.14"
tensorboard = ">=2.20.0,<3"
pyarrow = ">=24.0.0,<25"
array-api-compat = ">=1.14.0,<2"
ruff = ">=0.15.12,<0.16"
safetensors = ">=0.7.0,<0.8"
pytorch-gpu = ">=2.10.0,<3"

[pypi-dependencies]
torchviz = ">=0.0.3, <0.0.4"
ucimlrepo = ">=0.0.7, <0.0.8"
onnxscript = ">=0.7.0, <0.8"
