[project]
name = "pytorch"
version = "0.1.0"
description = "Pytorch"
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
start = "jupyter lab"

[dependencies]
pytorch = ">=2.1.2,<2.2"
python = ">=3.12,<3.13"
numpy = ">=1.26.4,<1.27"
jupyterlab = ">=4.1.3,<4.2"
matplotlib = ">=3.8.3,<3.9"
jupyterlab-myst = ">=2.3.2,<2.4"
tqdm = ">=4.66.2,<4.67"
scipy = ">=1.12.0,<1.13"
pip = ">=24.0,<25"
pandas = ">=2.2.1,<2.3"
requests = ">=2.31.0,<2.32"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.4.1.post1,<1.4.2"
torchvision = ">=0.16.1,<0.17"

[pypi-dependencies]
jupyterlab-rise = "*"
torchviz = "*"
graphviz = "*"
ucimlrepo = "*"
